version: "3"
services:
  dkron:
    build: .
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    environment:
      - GODEBUG=netdns=go
      - MONGO_URI=mongodb://mangafox:mangafox@mongo
    command: dkron agent --server --log-level=debug --bootstrap-expect=1
    depends_on:
      - mongo

  # mangareader-indexer:
  #   image: docker.pkg.github.com/manga-community/mangafox/mangafox:0.1.2
  #   entrypoint: ["/mangafox/mangareader-indexer"]
  #   environment:
  #     MONGO_URI: mongodb://mangafox:mangafox@mongo
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mangafox
      MONGO_INITDB_ROOT_PASSWORD: mangafox
    volumes:
      - mongo:/var/lib/mongo

volumes:
  mongo:
